In [51]:
import numpy as np
from scipy.linalg import lu as luDecomposition
from scipy.linalg import lu_factor as luFactor
from scipy.linalg import lu_solve as luSolver

# Funções Auxiliares

In [2]:
def updateX(matriz, lat, x, x_i, y_i): #diagonal superior
    try:
        matriz[x_i+1, y_i] = lat
    except:
        pass
    return x
    
def updateY(matriz, lat, y, x_i, y_i): # diagonal inferior
    try:
        matriz[x_i, y_i+1] = lat
    except:
        pass
    return y
def updateLatX(matriz, lat, x_i, y_i):
    try:
        matriz[x_i+3, y_i] = lat
    except:
        pass
def updateLatY(matriz, lat, x_i, y_i):
    try:
        matriz[x_i, y_i+3] = lat
    except:
        pass

# PVC1

In [90]:
N = 8
cel = N**2
cen = ((2*(N**2))+1)*(-1)
b = np.zeros((N-1))
b[-1] = cel
A = np.zeros((N-1, N-1))
for x_i, line in enumerate(A):
    for y_i, elm in enumerate(line):
        if x_i == y_i:
            A[x_i, y_i] = cen
            updateX(A, cel, 0, x_i, y_i)
            updateY(A, cel, 0, x_i, y_i)
A

array([[-129.,   64.,    0.,    0.,    0.,    0.,    0.],
       [  64., -129.,   64.,    0.,    0.,    0.,    0.],
       [   0.,   64., -129.,   64.,    0.,    0.,    0.],
       [   0.,    0.,   64., -129.,   64.,    0.,    0.],
       [   0.,    0.,    0.,   64., -129.,   64.,    0.],
       [   0.,    0.,    0.,    0.,   64., -129.,   64.],
       [   0.,    0.,    0.,    0.,    0.,   64., -129.]])

In [91]:
P, L, U = luDecomposition(A)

LU, p = luFactor(A)
result = luSolver((LU, p), b)
real = np.linalg.solve(A, b)
# np.allclose(result, real)
[(line, round(value, 8)) for line, value in (enumerate(result))]

[(0, -0.1066633),
 (1, -0.21499322),
 (2, -0.32668241),
 (3, -0.44347601),
 (4, -0.56719893),
 (5, -0.69978432),
 (6, -0.84330385)]

# PCV2

In [3]:
matriz = np.zeros((49, 49))
matriz.shape
x, y, ctr, lat = 3, 3, -256, 64
for x_i, line in enumerate(matriz):
    x -= 1
    for y_i, value in enumerate(line):    
        # define valor central
        if x_i == y_i:
            y -= 1
            matriz[x_i, y_i] = -256
            x = updateX(matriz, lat, x, x_i, y_i) if x > 0 else 3
            y = updateY(matriz, lat, y, x_i, y_i) if y > 0  else 3
            updateLatX(matriz, lat, x_i, y_i)
            updateLatY(matriz, lat, x_i, y_i)
matriz

array([[-256.,   64.,    0., ...,    0.,    0.,    0.],
       [  64., -256.,   64., ...,    0.,    0.,    0.],
       [   0.,   64., -256., ...,    0.,    0.,    0.],
       ...,
       [   0.,    0.,    0., ..., -256.,   64.,    0.],
       [   0.,    0.,    0., ...,   64., -256.,    0.],
       [   0.,    0.,    0., ...,    0.,    0., -256.]])

In [4]:
matriz[0:9, 0:9]

array([[-256.,   64.,    0.,   64.,    0.,    0.,    0.,    0.,    0.],
       [  64., -256.,   64.,    0.,   64.,    0.,    0.,    0.,    0.],
       [   0.,   64., -256.,    0.,    0.,   64.,    0.,    0.,    0.],
       [  64.,    0.,    0., -256.,   64.,    0.,   64.,    0.,    0.],
       [   0.,   64.,    0.,   64., -256.,   64.,    0.,   64.,    0.],
       [   0.,    0.,   64.,    0.,   64., -256.,    0.,    0.,   64.],
       [   0.,    0.,    0.,   64.,    0.,    0., -256.,   64.,    0.],
       [   0.,    0.,    0.,    0.,   64.,    0.,   64., -256.,   64.],
       [   0.,    0.,    0.,    0.,    0.,   64.,    0.,   64., -256.]])

In [5]:
open('matriz.txt', 'w').close()
f = open("matriz.txt", "a")
for line in matriz:
    st = ''
    for value in line:
        st = st + str(int(value)) + ' '
    print(st)
    f.write(st+'\n')
f.close()

-256 64 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
64 -256 64 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 64 -256 0 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
64 0 0 -256 64 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 64 0 64 -256 64 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 64 0 64 -256 0 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 64 0 0 -256 64 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 64 0 64 -256 64 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 64 0 64 -256 0 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 64 0 0 -256 64 0 64 0 0 0 0 0 0 0 0 0 0 0 0

# Solução Linear

In [65]:
b = np.ones((49))*4

In [71]:
P, L, U = luDecomposition(matriz)

LU, p = luFactor(matriz)
result = luSolver((LU, p), b)
real = np.linalg.solve(matriz, b)
# np.allclose(result, real)
[(line, round(value, 8)) for line, value in (enumerate(result))]

[(0, -0.05012435),
 (1, -0.06475584),
 (2, -0.05012435),
 (3, -0.07324156),
 (4, -0.09627467),
 (5, -0.07324156),
 (6, -0.08406722),
 (7, -0.11135971),
 (8, -0.08406722),
 (9, -0.08916762),
 (10, -0.11852972),
 (11, -0.08916762),
 (12, -0.09157352),
 (13, -0.12192395),
 (14, -0.09157352),
 (15, -0.09270253),
 (16, -0.12351902),
 (17, -0.09270252),
 (18, -0.09321759),
 (19, -0.12424709),
 (20, -0.09321753),
 (21, -0.09342074),
 (22, -0.12453421),
 (23, -0.09342052),
 (24, -0.09343115),
 (25, -0.12454849),
 (26, -0.09343035),
 (27, -0.09325539),
 (28, -0.12429825),
 (29, -0.09325237),
 (30, -0.09279215),
 (31, -0.12363675),
 (32, -0.09278089),
 (33, -0.09177648),
 (34, -0.1221757),
 (35, -0.09173443),
 (36, -0.08963805),
 (37, -0.11905513),
 (38, -0.08948114),
 (39, -0.0852206),
 (40, -0.11242565),
 (41, -0.08463499),
 (42, -0.0763187),
 (43, -0.09829188),
 (44, -0.07413316),
 (45, -0.05926232),
 (46, -0.06779),
 (47, -0.05110579),
 (48, -0.03044058)]

# Testes

In [79]:
c1, c2 = 1, 1
for x_i, line in enumerate(matriz):
    for y_i, value in enumerate(line):
        
        if x_i == y_i:
#             print(x_i, y_i)
            matriz[x_i, y_i] = -256
#             print(x_i <47)
            matriz[x_i-1, y_i] = 64 if x_i >= 0 else None
#             matriz[x_i+1, y_i] = 64 if x_i < 47 else None
            if x_i <= 48:
#                 print('aqui')
                matriz[x_i+1, y_i] = 64
            matriz[x_i, y_i-1] = 64 if y_i >= 0 else None
            if y_i <= 48:
                matriz[x_i, y_i+1] = 64

In [ ]:
f = open("demofile2.txt", "r")
print(f.read()) 

In [65]:
# a_file = open("test.txt", "w")

# for row in matriz:
#     print(row)
#     np.savetxt(a_file, row)

# a_file.close()

[-256.   64.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   64.]
[  64. -256.   64.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.]
[   0.   64. -256.   64.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.]
[   0.    0.   64. -256.   64.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.   